-- See docs/audit/01-BACKLOG-P0-P3.md [P3-06]: deleting a user previously
-- set Session.userId to NULL (ON DELETE SET NULL). A null-owner session is,
-- by this app's deliberate anonymous-session design, readable by anyone
-- holding its UUID (see interviewService.getOwnedSession) — so deleting an
-- account turned that account's interview sessions from private into
-- link-public instead of removing them. This changes the foreign key to
-- ON DELETE CASCADE, matching the pattern UserApiKey already uses.
--
-- Hand-written (not generated by `prisma migrate dev`) — this sandbox has
-- no network access to run the Prisma CLI. Written to match the format of
-- the existing 0_init migration exactly, and only touches the one
-- constraint schema.prisma's change actually affects. Please run
-- `npx prisma migrate deploy` (or `npx prisma migrate dev` in development)
-- against a real database to verify this applies cleanly before shipping.

-- DropForeignKey
ALTER TABLE "Session" DROP CONSTRAINT "Session_userId_fkey";

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
